---
name: CI

"on": [push]

jobs:
  vint:
    name: Vint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2.2.1
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install \
            vim-vint==$(grep vim-vint < neovim-requirements.txt | awk -F'==' '{print $2}')
      - name: vint
        run: |
          vint -c -s -t --enable-neovim $(git ls-files -- 'vim/*.vim' 'nvim/*.vim' vimrc)
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ludeeus/action-shellcheck@0.1.0
  requirements_txt:
    name: Validate Python requirements
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version:
          - 2.x
          - 3.x
        requirements:
          - python-system-requirements.txt
          - neovim-requirements.txt
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2.2.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: 1st pass
        run: pip install -r ${{ matrix.requirements }}
      - name: 2nd pass
        run: pip install -r ${{ matrix.requirements }}
  build:
    name: Build
    needs:
      - shellcheck
      - requirements_txt
    strategy:
      matrix:
        os:
          - ubuntu-20.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get update -qq
          sudo apt-get install apt-utils -yqq

          sudo apt-get install \
            locales \
            ssh \
            ca-certificates \
            lsb-release \
            build-essential \
            -yqq \
            --no-install-recommends

          sudo apt-get autoclean -yqq
          sudo apt-get autoremove -yqq
      - name: Setup timezone
        run: |
          echo 'tzdata tzdata/Zones/Europe select Warsaw' | sudo debconf-set-selections

          echo 'locales locales/locales_to_be_generated multiselect en_US.UTF-8 UTF-8' | sudo debconf-set-selections
          echo 'locales locales/default_environment_locale select en_US.UTF-8' | sudo debconf-set-selections
          echo 'keyboard-configuration  keyboard-configuration/layout select  English (UK)' | sudo debconf-set-selections

          sudo locale-gen en_US.UTF-8
          sudo ln -fs /usr/share/zoneinfo/Europe/Warsaw /etc/localtime

          sudo apt-get install tzdata -y --no-install-recommends
          sudo apt-get autoclean -yqq
          sudo apt-get autoremove -yqq
      - uses: actions/checkout@v2.3.4
      - name: kornicameister/dotfiles install
        run: |
          ./install \
            "${{ github.actor }}@kornicameiter.dotfiles.ci \
            "${{ github.actor }}" \
            "${{ github.job }}" \
            "${{ github.actor }}@kornicameiter.dotfiles.ci \
            "GHA Builds" \
            "${{ github.sha }}" \
            "555-WAKATIME-${{ github.run_id }}"
